name: laptopshop
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD-root}
      MYSQL_USER: laptopshop
      MYSQL_PASSWORD: laptopshop
      MYSQL_DATABASE: laptopshop
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./data/mysql:/var/lib/mysql
      # - ./laptopshop.sql:/docker-entrypoint-initdb.d/laptopshop.sql
