# 1: PROJECT_BACKEND_PORT
# 3: SONAR_PROJECT_KEY, SONAR_HOST_URL, SONAR_TOKEN
# 4: REGISTRY_URL, REGISTRY_PROJECT, REGISTRY_USER, REGISTRY_PASSWORD
variables:
  # registry.nnson128.io.vn/elroy/shoeshop:staging_0.0.11_4b1d2b6b
  DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_CONTAINER: ${CI_PROJECT_NAME}
stages:
  - build
  - sonarqube-scan
  - push
  - deploy
  - showlog

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker build -t ${DOCKER_IMAGE} .
  after_script:
    - docker logout ${REGISTRY_URL}
  tags: 
    - online-shop-runner-build-shell
  only:
    - tags


sonarqube-scan:
  stage: sonarqube-scan
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "Running SonarQube analysis..."
    - sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.sources=. -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN}
  tags: 
    - online-shop-runner-build-shell
  only:
    - tags
  allow_failure: true
  
push:
  stage: push
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker push ${DOCKER_IMAGE}
  after_script:
    - docker logout ${REGISTRY_URL}
  tags: 
    - online-shop-runner-build-shell
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull ${DOCKER_IMAGE}
    - docker rm -f ${DOCKER_CONTAINER} || echo "No existing container to remove"
    - docker run --name ${DOCKER_CONTAINER} -dp ${PROJECT_BACKEND_PORT}:${PROJECT_BACKEND_PORT} ${DOCKER_IMAGE}
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags

showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 20
    - docker logs ${DOCKER_CONTAINER}
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags
  when: manual
